export const GET_ALL_CUSTOMERS="GET_ALL_CUSTOMERS";
export const GET_UPDATED_CUSTOMER="GET_UPDATED_CUSTOMER";
export const GET_VIEW_CUSTOMER="GET_VIEW_CUSTOMER";
export const CUSTOMER_ADDED="CUSTOMER_ADDED";
export const ERROR_MESSAGE="ERROR_MESSAGE";
export const GET_DELETED_CUSTOMER="GET_DELETED_CUSTOMER";
